# Generated by Django 4.0.5 on 2022-06-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('shortname', models.CharField(max_length=128)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homm.title')),
            ],
        ),
    ]
