# Generated by Django 4.0.5 on 2022-06-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homm', '0002_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homm.title')),
            ],
        ),
    ]
