# Generated by Django 4.0.5 on 2022-06-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homm', '0003_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('disciplines', models.ManyToManyField(to='homm.discipline')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homm.faction')),
            ],
        ),
    ]
