# Generated by Django 4.0.5 on 2022-06-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homm', '0004_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'heroes'},
        ),
    ]
