# Generated by Django 4.0.5 on 2022-07-06 16:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homm', '0006_map'),
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=512)),
                ('shortname_ru', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=512)),
                ('shortname_en', models.CharField(max_length=128)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('is_official', models.BooleanField(default=True, verbose_name='Официальный турнир')),
                ('is_private', models.BooleanField(default=False, help_text='На этот турнир нет открытой регистрации.', verbose_name='Закрытый турнир')),
                ('forum_thread', models.CharField(help_text='Ссылка на тему турнира на форуме.', max_length=51, verbose_name='Тема турнира')),
                ('registration_is_opened', models.BooleanField(default=False, verbose_name='Регистрация открыта')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Турнир завершен')),
                ('maps', models.ManyToManyField(to='homm.map')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_registered', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации на турнир')),
                ('time_available', models.TextField(max_length=2048, verbose_name='Возможное время игры')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.tournament')),
            ],
            options={
                'db_table': 'reports_tournament_players',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, through='reports.TournamentPlayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
