# Generated by Django 4.0.5 on 2022-07-06 17:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homm', '0006_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(verbose_name='Дата начала отчета')),
                ('techresult', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('is_commited', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(null=True)),
                ('datetime_commited', models.DateTimeField(null=True, verbose_name='Дата завершения отчета')),
                ('datetime_confirmed', models.DateTimeField(null=True, verbose_name='Дата подтверждения/отклонения отчета')),
                ('player1_comment', models.TextField(blank=True, max_length=5000)),
                ('player2_comment', models.TextField(blank=True, max_length=5000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1_set', to='reports.tournamentplayer')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2_set', to='reports.tournamentplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата добавления игры')),
                ('winner', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('faction1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faction1_set', to='homm.faction')),
                ('faction2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faction2_set', to='homm.faction')),
                ('hero1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero1_set', to='homm.hero')),
                ('hero2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero2_set', to='homm.hero')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
