# Generated by Django 4.0.5 on 2022-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_tournamentplayer_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='has_started',
            field=models.BooleanField(default=False, verbose_name='Турнир стартовал'),
        ),
    ]
