# Generated by Django 4.0.5 on 2022-08-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homm', '0006_map'),
        ('reports', '0004_tournament_has_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='faction1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faction1_set', to='homm.faction'),
        ),
        migrations.AlterField(
            model_name='game',
            name='faction2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faction2_set', to='homm.faction'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hero1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero1_set', to='homm.hero'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hero2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero2_set', to='homm.hero'),
        ),
        migrations.AlterField(
            model_name='report',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала отчета'),
        ),
    ]
